// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoceaUniversitatiiDataModels;

#nullable disable

namespace vocea_universitatii.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class FacultyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormQuestion", b =>
                {
                    b.Property<long>("FormsId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionsId")
                        .HasColumnType("bigint");

                    b.HasKey("FormsId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("FormQuestion", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.AcademicYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AcademicYears", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndYear = 2023,
                            StartYear = 2022
                        },
                        new
                        {
                            Id = 2L,
                            EndYear = 2024,
                            StartYear = 2023
                        },
                        new
                        {
                            Id = 3L,
                            EndYear = 2025,
                            StartYear = 2024
                        });
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Activity", b =>
                {
                    b.Property<long>("DisciplineId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("DisciplineId", "ActivityTypeId", "TeacherId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.ActivityStudentCohort", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentCohortId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityTeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId", "StudentCohortId");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("StudentCohortId");

                    b.HasIndex("UpdatedByid");

                    b.HasIndex("ActivityDisciplineId", "ActivityTypeId", "ActivityTeacherId");

                    b.ToTable("ActivityStudentCohorts", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.ActivityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActivityTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Curs"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Seminar"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Laborator"
                        });
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Cohort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CohortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cohorts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CohortName = "Subgrupa"
                        },
                        new
                        {
                            Id = 2L,
                            CohortName = "Grupa"
                        },
                        new
                        {
                            Id = 3L,
                            CohortName = "Serie"
                        },
                        new
                        {
                            Id = 4L,
                            CohortName = "An"
                        });
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<long>("FacultyId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Discipline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AbsoluteSemester")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<long>("EvaluationMethodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Facultativ")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Optional")
                        .HasColumnType("boolean");

                    b.Property<long?>("ParentDisciplineId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudyProgramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("EvaluationMethodId");

                    b.HasIndex("ParentDisciplineId");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Disciplines", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.EvaluationMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("EvaluationMethods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Examen",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Colocviu",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Verificare",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Calificativ",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.EvaluationSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("EvaluationSessions", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Faculty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Faculties", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Form", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.FormQuestionInclusion", b =>
                {
                    b.Property<long>("FormId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("FormId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("FormQuestionInclusion", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LanguageName = "English"
                        },
                        new
                        {
                            Id = 2L,
                            LanguageName = "French"
                        },
                        new
                        {
                            Id = 3L,
                            LanguageName = "German"
                        },
                        new
                        {
                            Id = 4L,
                            LanguageName = "Romanian"
                        });
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<int>("LegacyFormOrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionAnswer")
                        .HasColumnType("text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.QuestionOptions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.QuestionScale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("UpdatedByid");

                    b.ToTable("QuestionScales", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudentCohort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint");

                    b.Property<long>("CohortTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentStudentCohortId")
                        .HasColumnType("bigint");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<long>("StudyProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudyYearId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CohortTypeId");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("ParentStudentCohortId");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("StudyYearId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("StudentCohorts", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<long>("FacultyId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("FacultyId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("StudyPrograms", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyProgramAcademicYearEnrollments", b =>
                {
                    b.Property<long>("StudyProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint");

                    b.HasKey("StudyProgramId", "AcademicYearId");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("StudyProgramAcademicYearEnrollments", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudyYears", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Anul I - Licență"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Anul II - Licență"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Anul III - Licență"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Anul IV - Licență"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Anul I - Master"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Anul II - Master"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Doctorat"
                        });
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TeacherTitleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("TeacherTitleId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.TeacherDepartmentMembership", b =>
                {
                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("BaseDepartment")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId", "DepartmentId");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("TeacherDepartmentMembership", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.TeacherTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("UpdatedByid");

                    b.ToTable("TeacherTitles", (string)null);
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FormQuestion", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.Form", null)
                        .WithMany()
                        .HasForeignKey("FormsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Activity", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("ActivityType");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.ActivityStudentCohort", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.StudentCohort", "StudentCohort")
                        .WithMany()
                        .HasForeignKey("StudentCohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityDisciplineId", "ActivityTypeId", "ActivityTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("StudentCohort");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Department", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Faculty");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Discipline", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.EvaluationMethod", "EvaluationMethod")
                        .WithMany("Disciplines")
                        .HasForeignKey("EvaluationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Discipline", "ParentDiscipline")
                        .WithMany("ChildOptionslDisciplines")
                        .HasForeignKey("ParentDisciplineId");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.StudyProgram", "StudyProgram")
                        .WithMany("Disciplines")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("EvaluationMethod");

                    b.Navigation("ParentDiscipline");

                    b.Navigation("StudyProgram");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.EvaluationMethod", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.EvaluationSession", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.AcademicYear", "AcademicYear")
                        .WithMany("EvaluationSessions")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Faculty", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Form", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Language", "Language")
                        .WithMany("Forms")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.FormQuestionInclusion", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.Form", "Form")
                        .WithMany("FormQuestionInclusions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Question", "Question")
                        .WithMany("FormQuestionInclusions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Question", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.QuestionOptions", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Question");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.QuestionScale", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Question", "Question")
                        .WithOne("QuestionScale")
                        .HasForeignKey("VoceaUniversitatiiDataModels.Models.QuestionScale", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Question");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudentCohort", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Cohort", "CohortType")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("CohortTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.StudentCohort", "ParentStudentCohort")
                        .WithMany()
                        .HasForeignKey("ParentStudentCohortId");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.StudyProgram", "StudyProgram")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.StudyYear", "StudyYear")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("StudyYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("AcademicYear");

                    b.Navigation("CohortType");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ParentStudentCohort");

                    b.Navigation("StudyProgram");

                    b.Navigation("StudyYear");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyProgram", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Faculty", "Faculty")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Language", "Language")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Faculty");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyProgramAcademicYearEnrollments", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudyProgramAcademicYearEnrollments")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.StudyProgram", "StudyProgram")
                        .WithMany("StudyProgramAcademicYearEnrollments")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Teacher", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.TeacherTitle", "Title")
                        .WithMany("Teachers")
                        .HasForeignKey("TeacherTitleId");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Title");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.TeacherDepartmentMembership", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Department", "Department")
                        .WithMany("TeacherDepartmentMemberships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.Teacher", "Teacher")
                        .WithMany("TeacherDepartmentMemberships")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Department");

                    b.Navigation("Teacher");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.TeacherTitle", b =>
                {
                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("VoceaUniversitatiiDataModels.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.AcademicYear", b =>
                {
                    b.Navigation("EvaluationSessions");

                    b.Navigation("StudentCohorts");

                    b.Navigation("StudyProgramAcademicYearEnrollments");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Cohort", b =>
                {
                    b.Navigation("StudentCohorts");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Department", b =>
                {
                    b.Navigation("TeacherDepartmentMemberships");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Discipline", b =>
                {
                    b.Navigation("ChildOptionslDisciplines");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.EvaluationMethod", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Form", b =>
                {
                    b.Navigation("FormQuestionInclusions");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Language", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Question", b =>
                {
                    b.Navigation("FormQuestionInclusions");

                    b.Navigation("QuestionOptions");

                    b.Navigation("QuestionScale");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyProgram", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("StudentCohorts");

                    b.Navigation("StudyProgramAcademicYearEnrollments");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.StudyYear", b =>
                {
                    b.Navigation("StudentCohorts");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.Teacher", b =>
                {
                    b.Navigation("TeacherDepartmentMemberships");
                });

            modelBuilder.Entity("VoceaUniversitatiiDataModels.Models.TeacherTitle", b =>
                {
                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
