// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoceaUniversitatii.Helpers;

#nullable disable

namespace vocea_universitatii.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231114180030_FixStudentCohort")]
    partial class FixStudentCohort
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vocea_universitatii.Models.AcademicYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AcademicYears");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndYear = 2023,
                            StartYear = 2022
                        },
                        new
                        {
                            Id = 2L,
                            EndYear = 2024,
                            StartYear = 2023
                        },
                        new
                        {
                            Id = 3L,
                            EndYear = 2025,
                            StartYear = 2024
                        });
                });

            modelBuilder.Entity("vocea_universitatii.Models.Cohort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CohortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cohorts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CohortName = "Subgrupa"
                        },
                        new
                        {
                            Id = 2L,
                            CohortName = "Grupa"
                        },
                        new
                        {
                            Id = 3L,
                            CohortName = "Serie"
                        },
                        new
                        {
                            Id = 4L,
                            CohortName = "An"
                        });
                });

            modelBuilder.Entity("vocea_universitatii.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<long>("FacultyId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Faculty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LanguageName = "English"
                        },
                        new
                        {
                            Id = 2L,
                            LanguageName = "French"
                        },
                        new
                        {
                            Id = 3L,
                            LanguageName = "German"
                        });
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudentCohort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint");

                    b.Property<long>("CohortTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentStudentCohortId")
                        .HasColumnType("bigint");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<long>("StudyProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudyYearId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CohortTypeId");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("ParentStudentCohortId");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("StudyYearId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("StudentCohorts");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<long>("FacultyId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("FacultyId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("StudyPrograms");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyProgramAcademicYearEnrollments", b =>
                {
                    b.Property<long>("StudyProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint");

                    b.HasKey("StudyProgramId", "AcademicYearId");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("StudyProgramAcademicYearEnrollments");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudyYears");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Anul I - Licență"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Anul II - Licență"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Anul III - Licență"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Anul IV - Licență"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Anul I - Master"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Anul II - Master"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Doctorat"
                        });
                });

            modelBuilder.Entity("vocea_universitatii.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CNP")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TeacherTitleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("TeacherTitleId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("vocea_universitatii.Models.TeacherDepartmentMembership", b =>
                {
                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("BaseDepartment")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId", "DepartmentId");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedByid");

                    b.ToTable("TeacherDepartmentMembership");
                });

            modelBuilder.Entity("vocea_universitatii.Models.TeacherTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByid")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByid");

                    b.HasIndex("DeletedByid");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("UpdatedByid");

                    b.ToTable("TeacherTitles");
                });

            modelBuilder.Entity("vocea_universitatii.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Department", b =>
                {
                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Faculty");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Faculty", b =>
                {
                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudentCohort", b =>
                {
                    b.HasOne("vocea_universitatii.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.Models.Cohort", "CohortType")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("CohortTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.Models.StudentCohort", "ParentStudentCohort")
                        .WithMany()
                        .HasForeignKey("ParentStudentCohortId");

                    b.HasOne("vocea_universitatii.Models.StudyProgram", "StudyProgram")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.Models.StudyYear", "StudyYear")
                        .WithMany("StudentCohorts")
                        .HasForeignKey("StudyYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("AcademicYear");

                    b.Navigation("CohortType");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ParentStudentCohort");

                    b.Navigation("StudyProgram");

                    b.Navigation("StudyYear");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyProgram", b =>
                {
                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.Models.Faculty", "Faculty")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.Models.Language", "Language")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Faculty");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyProgramAcademicYearEnrollments", b =>
                {
                    b.HasOne("vocea_universitatii.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudyProgramAcademicYearEnrollments")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.Models.StudyProgram", "StudyProgram")
                        .WithMany("StudyProgramAcademicYearEnrollments")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Teacher", b =>
                {
                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.Models.TeacherTitle", "Title")
                        .WithMany("Teachers")
                        .HasForeignKey("TeacherTitleId");

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Title");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.TeacherDepartmentMembership", b =>
                {
                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.Models.Department", "Department")
                        .WithMany("TeacherDepartmentMemberships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.Models.Teacher", "Teacher")
                        .WithMany("TeacherDepartmentMemberships")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Department");

                    b.Navigation("Teacher");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.TeacherTitle", b =>
                {
                    b.HasOne("vocea_universitatii.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByid");

                    b.HasOne("vocea_universitatii.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByid");

                    b.HasOne("vocea_universitatii.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByid");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("vocea_universitatii.Models.AcademicYear", b =>
                {
                    b.Navigation("StudentCohorts");

                    b.Navigation("StudyProgramAcademicYearEnrollments");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Cohort", b =>
                {
                    b.Navigation("StudentCohorts");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Department", b =>
                {
                    b.Navigation("TeacherDepartmentMemberships");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Language", b =>
                {
                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyProgram", b =>
                {
                    b.Navigation("StudentCohorts");

                    b.Navigation("StudyProgramAcademicYearEnrollments");
                });

            modelBuilder.Entity("vocea_universitatii.Models.StudyYear", b =>
                {
                    b.Navigation("StudentCohorts");
                });

            modelBuilder.Entity("vocea_universitatii.Models.Teacher", b =>
                {
                    b.Navigation("TeacherDepartmentMemberships");
                });

            modelBuilder.Entity("vocea_universitatii.Models.TeacherTitle", b =>
                {
                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
